### ISSUE TITLE
JSON error

### ISSUE THREAD

**Issue by ehmicky** [philhawksworth/netlify-plugin-add-instagram#5]
The following error happens in a build (on a Site that is probably yours: https://app.netlify.com/sites/hawksworx/deploys/5ed623966b072e000604dd7d):

```
invalid json response body at https://www.instagram.com/accounts/login/?next=/philhawksworth/%3F__a%3D1 reason: Unexpected token < in JSON at position 0 
    /opt/build/repo/node_modules/node-fetch/lib/index.js:272:32 
    internal/process/next_tick.js:68:7 process._tickCallback
```

It looks like the problem might be that the HTTP response is assumed to be JSON where it's receiving some HTML back instead. Do you have some insights?

**Comment by philhawksworth** [comment]
Thanks @ehmicky. I just spotted this reported in a recent failed build (correctly reporwed as failing due to the plugin, so that's good).

Looks like I need to make this more resilient if the Instagram API returns something unexpected.

Investigating.

**Comment by philhawksworth** [comment]
v0.2.3 adds checking of the response type and gracefully failing the plugin (but not the build) if JSON is not returned for some reason.
Thanks for reporting this, @ehmicky.

**Comment by ehmicky** [comment]
Thanks @philhawksworth! :tada: 
Would it be possible for you to update the version in `netlify/plugins`? This will allow UI installations of this plugin to benefit from the fix. Thanks a lot!
